<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Internship;

class InternshipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Internship::truncate();

        Internship::create([
            'nazwa' => "Dziennikarstwo",
            'opis' => "Dziennikarz, dziennikarka – osoba zajmująca się przygotowaniem i prezentowaniem materiałów w środkach masowego przekazu.Pierwotnie termin ten oznaczał osobę piszącą teksty w gazetach, ale wraz z rozwojem innych mediów, objął także osoby zajmujące się przygotowaniem tekstów w radiu, telewizji oraz internecie. Podstawowym zajęciem dziennikarza jest dostarczanie odbiorcy wartościowych informacji, najczęściej dotyczących bieżących wydarzeń. Osoba pracująca na tym stanowisku tworzy inne gatunki dziennikarskie, takie jak reportaże, felietony, newsy i inne. W dobie internetu przygotowuje również materiały audio i video oraz robi zdjęcia, które są publikowane w sieci np. na portalach i serwisach informacyjnych.",
            'obowiązki' => "zbieranie i interpretacja informacji pod kątem przydatności do wykorzystania w tworzeniu publikacji;\npisanie i redakcja tekstów o zróżnicowanej tematyce, stylistyce, realizujących różnorodne reguły gatunkowe i cele komunikacyjne;\nwsparcie obsługi strony internetowej w ramach publikacji tekstów;\nwspółpraca z grafikami, fotoreporterami i działem technicznym w celu nadania odpowiedniego kształtu graficznego i wizualnego materiałom przeznaczonym do publikacji (m.in. Adobe Photoshop);\nutrzymywanie kontaktu z odbiorcami (czytelnikami) w celu poznania ich zainteresowań i opinii lub wpływania na nią przy wykorzystaniu social mediów;\nuczestniczenie w dialogu społecznym na ważne i aktualne tematy, kształtowanie postaw sprzyjających przestrzeganiu demokratycznych reguł życia społecznego i politycznego;\nadministracja portali należących do Fundacji, w tym redagowanie, korekta i publikowanie artykułów, dbanie o porządek zamieszczanych treści, aktualizowanie danych na portalach (tylko w przypadku praktyk dłuższych niż 160 h).",
            'narzędzia' => "Google Analytics\nGoogle Zeitgeist\nActionScript\nAPI\nChartPart",
            'obraz' => "/images/internships/dziennikarstwo.png"
        ]);

        Internship::create([
            'nazwa' => "Wschodoznawstwo",
            'opis' => "Fundacja na Rzecz Promocji i Rozwoju „Głos Młodych” zaprasza na praktyki z zakresu wschodoznawstwa! Zapraszamy do zapoznania się ze stroną internetową najnowszego Projektu ,,Głos Wschodu’’ oraz towarzyszącemu mu portalowi o takiej samej nazwie „Głos Wschodu”, który ma na celu przekazywanie wiedzy i doświadczeń w konkretnych dziedzinach Państw Wschodu: https://gloswschodu.pl.",
            'obowiązki' => "zapoznanie się z daną organizacją i zasadami jej funkcjonowania (forma prawna, struktura organizacyjna, zasady organizacji pracy i podziału kompetencji, procedury, procesy planowania i kontroli)\nzapoznanie się zasadami przepływu informacji i dokumentacji w ramach organizacji\nzdobycie wiedzy językoznawczej, literaturoznawczej i kulturoznawczej związanej z terenami dawnego Związku Radzieckiego\nzdobycie wiedzy o historii i aktualnej sytuacji Państw Wschodu\nnabycie umiejętności analizowania problemów społecznych, politycznych, ekonomicznych, prawnych, kulturowych, etnicznych i religijnych Europy Wschodniej, Azji Środkowej, Kaukazu i Syberii\npoznanie podstawowych zasad dyplomatycznych i ich stosowania w praktyce\nzdobycie wiedzy o podstawowych technikach promocji na arenie międzynarodowej\nnabycie umiejętności analizowania procesów komunikowania na arenie międzynarodowej\nzdobycie wiedzy o różnych rodzajach struktur i instytucji społecznych (kulturowych, politycznych, prawnych, ekonomicznych, związanych z bezpieczeństwem, ekologicznych, kulturalnych) działających w środowisku międzynarodowym\nzdobycie wiedzy o relacjach między strukturami i instytucjami społecznymi w skali krajowej, międzynarodowej i międzykulturowej\nzapoznanie się z zasadami i formami współpracy zagranicznej organizacji lub ich działalności na rzecz propagowania i rozwoju działań transgranicznych\nzdobycie wiedzy o normach i regułach (prawnych, organizacyjnych, moralnych, etycznych) organizujących struktury i instytucje społeczne w dziedzinie stosunków międzynarodowych i rządzących nimi prawidłowościach oraz o ich źródłach, naturze, zmianach i sposobach działania\nzdobycie wiedzy o poglądach na temat struktur i instytucji społecznych działających w środowisku międzynarodowym oraz rodzajów więzi społecznych i o ich historycznej ewolucji\npoznanie fundamentalnych dylematów współczesnej cywilizacji i jej uwarunkowań międzynarodowych\ntworzenie sieci kontaktów z organizacjami i osobami działającymi na terenie lub na rzecz Państw Wschodu\ntworzenie i wysyłanie ofert współpracy do organizacji działających na terenie lub na rzecz Państw Wschodu przy zastosowaniu zasad dyplomatycznych\nkreowanie pozytywnego wizerunku Fundacji wśród organizacji i osób związanych z Państwami Wschodu przy wykorzystaniu social mediów\nprzygotowanie opracowań na temat wybranego rejonu Europy Wschodniej, Kaukazu Południowego, Azji Środkowej lub Syberii i występujących tam zjawisk społeczno–gospodarczo-kulturowych\nwspółudział w organizacji projektów międzynarodowych Fundacji\nwspółtworzenie strategii komunikacji oraz rozwoju Fundacji na arenie międzynarodowej\nkontakt telefoniczny i e-mailowy z interesariuszami i organizacjami działającymi na terenie lub na rzecz Europy Wschodniej, Kaukazu Południowego, Azji Środkowej i Syberii\nwykonywanie innych zadań zleconych",
            'narzędzia' => "minimalny wymiar godzinowy praktyk – 160 h\nstatus studenta (preferowane kierunki: wschodoznawstwo oraz pokrewne) – przy praktykach uczelnianych• zainteresowanie polityką, gospodarką kulturą, nauką, turystyką i biznesem Państw Wschodu\nznajomość pakietu MS Office\nsamodzielność, dobra organizacja pracy, umiejętność pracy zespołowej\nzaangażowanie, sumienność i dokładność w wykonywaniu zadań\nefektywne komunikowanie się z otoczeniem w miejscu pracy\nwysoka kultura osobista\ngotowość do nauki nowych rzeczy\nchęć zdobycia praktycznej wiedzy z zakresu wschodoznawstwa",
            'obraz' => "/images/internships/wschodoznawstwo.png"
        ]);

        Internship::create([
            'nazwa' => "Stosunki Międzynarodowe",
            'opis' => null,
            'obowiązki' => "zapoznanie się z daną organizacją i zasadami jej funkcjonowania (forma prawna, struktura organizacyjna, zasady organizacji pracy i podziału kompetencji, procedury, procesy planowania i kontroli)\nzapoznanie się zasadami przepływu informacji i dokumentacji w ramach organizacji\nzdobycie wiedzy o różnych rodzajach struktur i instytucji społecznych (kulturowych, politycznych, prawnych, ekonomicznych, związanych z bezpieczeństwem, ekologicznych, kulturalnych) działających w środowisku międzynarodowym\n zdobycie wiedzy o relacjach między strukturami i instytucjami społecznymi w skali krajowej, międzynarodowej i międzykulturowej\nzapoznanie się z zasadami i formami współpracy zagranicznej organizacji lub ich działalności na rzecz propagowania i rozwoju działań transgranicznych\npoznanie podstawowych metod i narzędzi, w tym technik pozyskiwania danych, pozwalających opisywać struktury i instytucje społeczne działające w środowisku międzynarodowym oraz procesy w nich i między nimi zachodzące\nzdobycie wiedzy o normach i regułach (prawnych, organizacyjnych, moralnych, etycznych) organizujących struktury i instytucje społeczne w dziedzinie stosunków międzynarodowych i rządzących nimi prawidłowościach oraz o ich źródłach, naturze, zmianach i sposobach działania\nzdobycie wiedzy o poglądach na temat struktur i instytucji społecznych działających w środowisku międzynarodowym oraz rodzajów więzi społecznych i o ich historycznej ewolucji\npoznanie fundamentalnych dylematów współczesnej cywilizacji i jej uwarunkowań międzynarodowych\ninterpretowanie zjawisk społecznych (kulturowych, politycznych, prawnych, ekonomicznych) w obszarze stosunków międzynarodowych\nanalizowanie i interpretacja statystyk z różnych dziedzin stosunków międzynarodowych\nprognozowanie procesów i zjawisk społecznych (kulturowych, politycznych, prawnych, ekonomicznych) z wykorzystaniem standardowych metod i narzędzi w dziedzinie stosunków międzynarodowych\ninterpretowanie norm i reguł (prawnych, zawodowych, moralnych) w celu rozwiązania konkretnego problemu z dziedziny stosunków międzynarodowych\nprzygotowywanie opracowań, prezentacji, analiz dotyczących zjawisk i organizacji międzynarodowych\nprzygotowywanie planów współpracy organizacji z instytucjami międzynarodowymi lub obcokrajowcami\nkontakt telefoniczny i e-mailowy z interesariuszami i organizacjami działającymi na arenie międzynarodowej\nwykonywanie innych zadań zleconych z zakresu stosunków międzynarodowych",
            'narzędzia' => "minimalny wymiar godzinowy praktyk – 160 h\nstatus studenta (preferowane kierunki: stosunki międzynarodowe, międzynarodowe stosunki gospodarcze oraz pokrewne) – przy praktykach uczelnianych\nznajomość pakietu MS Office\nsamodzielność, dobra organizacja pracy, umiejętność pracy zespołowej\nzaangażowanie, sumienność i dokładność w wykonywaniu zadań\nefektywne komunikowanie się z otoczeniem w miejscu pracy\nwysoka kultura osobista\ngotowość do nauki nowych rzeczy\nchęć zdobycia praktycznej wiedzy z zakresu stosunków międzynarodowych",
            'obraz' => "/images/internships/stosunki_miedzynarodowe.png"
        ]);

        Internship::create([
            'nazwa' => "Tłumacz",
            'opis' => "Tłumacz zajmuje się przekładem wypowiedzi lub tekstu pisanego z języka źródłowego na język docelowy wykorzystując znajomość co najmniej dwóch języków. Na tym stanowisku konieczna jest perfekcyjna znajomość języka obcego, jak i ojczystego, zasad gramatyki, ortografii i tzw. ,,lekkie pióro’’.",
            'obowiązki' => "znajdowanie ciekawych artykułów i publikacji zagranicznych do tłumaczenia;\npisemne tłumaczenie różnych tekstów znajdujących się na zagranicznych serwisach internetowych takich jak: Business Insider, The New York Times, CNN, Le Figaro, Die Welt itp., serwisach naukowych, portalach specjalistycznych, blogach i innych przy zachowaniu jak największej zgodności pomiędzy tekstem źródłowym a tłumaczeniem, nie tylko pod względem merytorycznym, ale także językowym i stylistycznym.",
            'narzędzia' => "Zróżnicowana tematyka tekstów. Tematyka tłumaczonych materiałów musi być różna i to tłumacz samodzielne ją dobiera, jeżeli uzna, że zaciekawi ona czytelnika. Ważne jest, aby tłumaczone teksty nie były monotematyczne.\nPodanie źródła i danych autora i tłumacza. Pod każdym przetłumaczonym artykułem praktykant praktyk uczelnianych / pozauczelnianych podaje źródło i autora oraz imię i nazwisko osoby tłumaczącej.\nRedakcja tekstu. Każdy artykuł jest sprawdzany przez redakcje, a błędy są poprawiane.\nPublikacja tekstu. Poprawione teksty są zamieszczane na portale, z którymi współpracuje Fundacja i których wydawcą jest fundacja: https://pressglobal.pl/, http://www.plportal.pl oraz https://gloswschodu.pl.\nWymiar praktyk. Minimalny wymiar praktyk wynosi 160 godzin i swoim zakresem obejmuje 25 artykułów. Możliwa jest realizacja praktyk o niższym wymiarze godzinowym,  liczba artykułów do przetłumaczenia pozostaje proporcjonalnie zmniejszona/  taka sama ().  W przypadku większej ilości godzin  WSB. Tischner, Collegium Civitas. Ateneum, inne uczelnie- praktyki są modułowe i podzielone na dwie tury.",
            'obraz' => "/images/internships/tlumacz.png"
        ]);

        Internship::create([
            'nazwa' => "Europeistyka",
            'opis' => null,
            'obowiązki' => "zapoznanie się z daną organizacją i zasadami jej funkcjonowania (forma prawna, struktura organizacyjna, zasady organizacji pracy i podziału kompetencji, procedury, procesy planowania i kontroli)\nzapoznanie się zasadami przepływu informacji i dokumentacji w ramach organizacji\nzdobycie wiedzy na temat funkcjonowania Unii Europejskiej i jej wpływu na działalność organizacji\nzdobycie umiejętności dotarcia do potrzebnych informacji i dokumentów Unii Europejskiej\nzdobycie umiejętności interpretacji informacji, dokumentów i prawa Unii Europejskiej\nzapoznanie się z informacjami dotyczącymi funduszy UE dla poszczególnych podmiotów\nzapoznanie się z organizacją pracy na stanowisku osoby zajmującej się projektami realizowanymi ze środków unijnych (dokumentacją potrzebną do pracy, generatorem wniosków aplikacyjnych, rolą kierownika projektu)\nzapoznanie się z procedurami aplikacyjnymi oraz zasadami przygotowania i zarządzania projektami realizowanymi ze środków funduszy UE\nzapoznanie się z zasadami korzystania ze środków unijnych\nwyszukiwanie określonych informacji i dokumentów Unii Europejskiej na potrzeby organizacji\ninterpretację przepisów prawa Unii Europejskiej\nwyszukiwanie możliwości pozyskania funduszy europejskich dla organizacji oraz określenie formalności, które należy spełnić, aby je uzyskać\nzdobycie umiejętności przygotowania opracowań dotyczących określonej tematyki związanej z Unią Europejską\nzdobycie wiedzy o podstawowych technikach promocji na arenie międzynarodowej\nnabycie umiejętności analizowania procesów komunikowania na arenie międzynarodowej\nzdobycie wiedzy o różnych rodzajach struktur i instytucji społecznych działających na arenie Unii Europejskiej\nzapoznanie się z zasadami i formami współpracy zagranicznej organizacji lub ich działalności na rzecz propagowania i rozwoju działań transgranicznych\nprzygotowywanie pism, raportów, opracowań na potrzeby organizacji\nwspółudział w tworzeniu projektu unijnego\nwspółudział w koordynowaniu działań w ramach projektu unijnego\nwspółtworzenie strategii komunikacji oraz rozwoju Fundacji na arenie Unii Europejskiej\nkontakt telefoniczny i e-mailowy z interesariuszami organizacji\nwykonywanie innych zadań zleconych\narchiwizację dokumentacji prawniczej",
            'narzędzia' => "minimalny wymiar godzinowy praktyk – 160 h\nstatus studenta (preferowane kierunki: europeistyka, prawo europejskie oraz pokrewne) – przy praktykach uczelnianych\nzainteresowanie problemami integracji europejskiej, zagadnieniami związanymi z wykorzystaniem funduszy unijnych, europejską sceną polityczną, rozwojem i współpracą regionalną w Europie, historią, kulturą Europy czy funkcjonowaniem administracji unijnej\nznajomość pakietu MS Office\nsamodzielność, dobra organizacja pracy, umiejętność pracy zespołowej\nzaangażowanie, sumienność i dokładność w wykonywaniu zadań\nefektywne komunikowanie się z otoczeniem w miejscu pracy\nwysoka kultura osobista\ngotowość do nauki nowych rzeczy\nchęć zdobycia praktycznej wiedzy z zakresu europeistyki bądź prawa europejskiego",
            'obraz' => "/images/internships/europeistyka.png"
        ]);

        Internship::create([
            'nazwa' => "Programista",
            'opis' => "Programista – osoba zajmująca się tworzeniem i rozwojem oprogramowania np. programów zarządzających bazami danych, programów aplikacyjnych (np. edytory), systemowych, narzędziowych.",
            'obowiązki' => "tworzenie i administracja stronami WWW;\ntworzenie, administracja i użytkowanie relacyjnymi bazami danych przy wykorzystaniu wybranych systemów np. MySQL;\ntworzenie i administracja systemami zarządzania treścią;\nprogramowanie i testowanie aplikacji internetowych przy wykorzystaniu wybranych języków np. PHP, Java, C#;\nprojektowanie, programowanie i testowanie aplikacji desktopowych przy wykorzystaniu wybranych narzędzi m.in. .NET Framework, Visual Studio;\nuczestniczenie w tworzeniu narzędzi wspierających proces testowania;\nrozwijanie systemów operacyjnych, systemów zarządzania bazami danych, sterowników;\nwyszukiwanie i usuwanie błędów powstałych w trakcie pisania kodu (debugowanie);\ntestowanie i zapewnienie jakości tworzonego oprogramowania.",
            'narzędzia' => "Issue Tracker\nTrello\nJira\nGIT\nGitHub\nEclipse\nVisual Studio Code\nFramework",
            'obraz' => "/images/internships/programista.png"
        ]);

        Internship::create([
            'nazwa' => "Informatyk",
            'opis' => "Informatyk to osoba, która zajmuje się tworzeniem przekształcaniem i przekazywaniem danych za pomocą programów komputerowych. Do tego celu musi posiadać podstawową wiedzę na temat tworzenia i przetwarzania informacji, a także budowy i zasad działania urządzeń komputerowych.",
            'obowiązki' => "pomoc w usuwaniu bieżących problemów sprzętowych i programowych;\npomoc w obsłudze aplikacji wykorzystywanych w danym podmiocie;\ninstalowanie systemów operacyjnych, nowego oprogramowania, sterowników urządzeń np. kart sieciowych, graficznych, muzycznych itp.;\nadministrowanie siecią lokalną lub rozległą np. tworzenie użytkowników sieciowych i nadawanie im praw, udostępnianie urządzeń sieciowych i zasobów dyskowych, wykonywanie kopii zawartości dysku;\nbieżąca konserwacja i naprawa sprzętu komputerowego;\nochrona danych, programów i procesów przetwarzania, struktura danych dla określonego zagadnienia przetwarzania, oprogramowanie użytkowe w danym przedsiębiorstwie, zakres stosowania, cechy eksploatacyjne, zasady obsługi;\nkontrola poprawności procesu przetwarzania, biblioteki oprogramowania i zbiorów danych;\nopracowywanie stron WWW lub tworzenie prezentacji multimedialnych;\ntworzenie aplikacji informatycznych z wykorzystaniem wybranych języków programowania.",
            'narzędzia' => "Everest Home Edition\nWho Crashed\nCcleaner\nAutoruns\nPCMARK\nTest Disk & Photo Rec",
            'obraz' => "/images/internships/informatyk.png"
        ]);

        Internship::create([
            'nazwa' => "Marketing Internetowy",
            'opis' => "Marketing internetowy to wszelkie działania mające na celu opracowanie strategii dla wprowadzenia produktu na rynek, jego promocji oraz przedstawienie w korzystny sposób marki przy wykorzystaniu internetu.",
            'obowiązki' => "projektowanie i rozwój zaplecza dedykowanego pod pozycjonowanie;\nprowadzenie projektów SEO;\nrealizacja kampanii content marketingowych;\nwsparcie w działaniach PR;\nanaliza przeprowadzanych działań;\ntworzenie krótkich tekstów o określonej tematyce;\ntworzenie artykułów dla wybranych projektów SEO.",
            'narzędzia' => "Google Analytics\nFreshmail\nSalesManago\nGoogle Trends\nWordPress\nBrand24",
            'obraz' => "/images/internships/marketing_internetowy.png"
        ]);

        Internship::create([
            'nazwa' => "Grafik",
            'opis' => "Grafik zajmuje się tworzeniem zajmują się tworzeniem różnych projektów graficznych przy użyciu dedykowanych do tego programów komputerowych np. Adobe Photoshop czy Corel Draw. Osoba na tym stanowisku musi wykazać się wysoką kreatywnością i przy każdym projekcie tworzyć niebanalne grafiki.",
            'obowiązki' => "projektowanie logo oraz banerów;\nprojektowanie makiet stron internetowych;\ntworzenie i opracowanie materiałów graficznych (piktogramów i logotypów) na potrzeby działań reklamowych oraz komunikacyjnych;\ntworzenie projektów banerów pod Google Ads;\ntworzenie projektów i grafik promocyjnych udostępnianych w social mediach.",
            'narzędzia' => "Adobe Illustrator\nAdobe Photoshop\nAdobe InDesign\nPhotoScape\nCorel Draw\nBlender 3D\nGIMP",
            'obraz' => "/images/internships/grafik.png"
        ]);

        Internship::create([
            'nazwa' => "SEO Copywriter",
            'opis' => "SEO copywriter zajmuje się opracowywaniem tekstów na potrzeby działań SEO, które sązwiązane z pozycjonowaniem. Osoba na tym stanowisku tworzy wartościowy tekst, ale dba też o jego optymalizację (słowa kluczowe, układ tekstu, nagłówki, title czy description). Konieczne jest posiadanie przynajmniej podstawowej wiedzy dotyczącej pozycjonowania, ale też przygotowywanie poprawnych językowo treści.",
            'obowiązki' => "przygotowywanie tekstów o charakterze reklamowo-informacyjnym przy uwzględnieniu zasad pozycjonowania stron (słowa kluczowe, układ tekstu, nagłówki, title czy description);\nanaliza istniejących tekstów oraz ich ewentualna korekta przy uwzględnieniu kryterium pozycjonowania stron (frazy kluczowe);\nwprowadzanie do istniejących tekstów treści nawigacji tekstem (linki odsyłające);\nbudowanie bazy linków kierujących na daną stronę (link building);\ntworzenie map witryny XML i zarządzanie nią przy wykorzystywaniu wtyczki Yoast SEO;\nwykonywanie audytu SEO stron internetowych;\nprowadzenie promocji danego podmiotu poprzez prowadzenie kampanii PPC przy wykorzystaniu Google Ads;\ntworzenie słów kluczowych dla reklam Google przy wykorzystaniu Adwords Key Planner;\nwykorzystywanie narzędzi do analizy korelacji czynników on-page i prowadzeniem badań konkurencji (np. SurferSEO);\nobsługa oprogramowania do analizy widoczności i pozycji;\nstosowanie tzw. crawlerów analizujących strukturę i wydajność strony.",
            'narzędzia' => "Google Analytics\nGoogle Trends\nGoogle AdWords\nGoogle KeyWord Planner\nGoogle Search Console\nYoast SEO\nCoSchedule Headline Analyzer\nWordConuter\nPlagiator\nPixabay\nCanva\nSeoBook\nGIMP",
            'obraz' => "/images/internships/seo_copywriter.png"
        ]);

        Internship::create([
            'nazwa' => "Copywriter",
            'opis' => "Copywriter zajmuje się głównie pisaniem różnego typu tekstów, artykułów i opisów firm, produktów, usług i wydarzeń na strony internetowe. Copywriter kreatywny specjalizuje się w układaniu sloganów, haseł reklamowych, wymyślaniu nazw firm oraz produktów. Obmyśla także koncepcje reklam i układa do nich scenariusze. Content writer zwany także web writerem, ponieważ tworzy treści, które w głównej mierze są publikowane w sieci. Są to przede wszystkim teksty na stronach internetowych, wpisy na blogach, oferty, teksty do komunikacji z mediami, mailingi. Ponadto content writer układa teksty ulotek czy folderów. SEO copywriter tworzy materiały zgodne z zasadami pozycjonowania. Są to najczęściej treści pod wyszukiwarki, ale też wpisy blogowe.",
            'obowiązki' => "zbieranie i interpretacja informacji pod kątem przydatności do tworzenia przyszłych publikacji;\ntworzenie tekstów reklamowych, haseł reklamowych, sloganów, scenariuszy filmów reklamowych i innych;\nanaliza istniejących tekstów oraz ich ewentualna zmiana na język reklamowy;\nokreślanie tematów, które zyskują na popularności (Google Trends) i tworzenie nowych propozycji przy wykorzystaniu dedykowanych do tego programów;\nporównywanie zawartości powstałych tekstów do tych istniejących w internecie przy wykorzystaniu programów antyplagiatowych np. Rapidus;\npoprawianie błędów gramatycznych i składniowych tekstów i ich ewentualna korekta;\nanalizowanie czytelności i dostosowanie tekstu do standardów SEO przy wykorzystaniu wtyczki Yoast SEO;\nuzupełnianie tekstów o dodatkową szatę graficzną przyciągającą uwagę przy wykorzystaniu baz grafik np. Pixabay.",
            'narzędzia' => "Google Keyword Planner lub KWFinder\nAnswerThePublic\nGoogle Trends\nRapidus\nCopywritely\nYoast SEO\nPixabay",
            'obraz' => "/images/internships/copywriter.png"
        ]);

        Internship::create([
            'nazwa' => "Specjalista ds. social media",
            'opis' => "Specjalista ds. social media to stanowisko z branży digital marketingu, które mogą objąć osoby z dużym doświadczeniem w zarządzaniu kanałami społecznościowymi marek. Wymaga ono wszechstronnej wiedzy z zakresu marketingu, PR-u, psychologii zachowań w internecie, analityki, reklam, e-commerce i szeroko pojętego biznesu.",
            'obowiązki' => "prowadzenie profili w social-media (Facebook, Instagram i inne);\nbudowanie strategii działań w kanałach social media;\nopracowywanie działań marketingowych wspierających komunikację Fundacji;\nplanowanie i tworzenie treści w mediach społecznościowych;\nmonitoring i raportowanie skuteczności działań;\nkreowanie angażującego contentu w ścisłej współpracy z działami marketingu, graficznym oraz IT;\nresearch, pozyskiwanie oraz budowanie długofalowej współpracy z influencerami;\nkontrolowanie powierzonego budżetu oraz optymalizowanie działań w obszarze influencer marketingu;\nmonitorowanie i raportowanie wyników prowadzonych kampanii oraz zasięgów tworzonych treści;\nśledzenie i analizowanie aktualnych trendów, a także monitorowanie bieżących działań konkurencji.",
            'narzędzia' => "Brand24\nMeet Edgar\nAdobe Spark\nSlack\nFacebook Audience Insights\nPhotoshop",
            'obraz' => "/images/internships/specjalista_ds_social_media.png"
        ]);

        Internship::create([
            'nazwa' => "Marketing Polityczny",
            'opis' => null,
            'obowiązki' => "zapoznanie się z daną organizacją i zasadami jej funkcjonowania (forma prawna, struktura organizacyjna, zasady organizacji pracy i podziału kompetencji, procedury, procesy planowania i kontroli)\nzapoznanie się zasadami przepływu informacji i dokumentacji w ramach organizacji\nzdobycie wiedzy o podstawowych technikach promocji na arenie międzynarodowej\nnabycie umiejętności analizowania procesów komunikowania na arenie międzynarodowej\nzdobycie wiedzy o różnych rodzajach struktur i instytucji społecznych (kulturowych, politycznych, prawnych, ekonomicznych, związanych z bezpieczeństwem, ekologicznych, kulturalnych) działających w środowisku międzynarodowym\nzdobycie wiedzy o relacjach między strukturami i instytucjami społecznymi w skali krajowej, międzynarodowej i międzykulturowej\nzapoznanie się z zasadami i formami współpracy zagranicznej organizacji lub ich działalności na rzecz propagowania i rozwoju działań transgranicznych\npoznanie podstawowych metod i narzędzi, w tym technik pozyskiwania danych, pozwalających opisywać struktury i instytucje społeczne działające w środowisku międzynarodowym oraz procesy w nich i między nimi zachodzące\nzdobycie wiedzy o normach i regułach (prawnych, organizacyjnych, moralnych, etycznych) organizujących struktury i instytucje społeczne w dziedzinie stosunków międzynarodowych i rządzących nimi prawidłowościach oraz o ich źródłach, naturze, zmianach i sposobach działania\nzdobycie wiedzy o poglądach na temat struktur i instytucji społecznych działających w środowisku międzynarodowym oraz rodzajów więzi społecznych i o ich historycznej ewolucji\npoznanie fundamentalnych dylematów współczesnej cywilizacji i jej uwarunkowań międzynarodowych\ntworzenie ofert współpracy z instytucjami z kraju i za granicy\nkreowanie wizerunku Fundacji na arenie krajowej i międzynarodowej przy wykorzystaniu social mediów\nwykorzystanie narzędzi do promocji działań Fundacji w Polsce, jak i za granicą przy wykorzystaniu social mediów\nwspółudział w organizacji projektów międzynarodowych Fundacji\nwspółtworzenie strategii komunikacji oraz rozwoju Fundacji na arenie międzynarodowej\nnawiązywanie i utrzymywanie kontaktów z mediami krajowymi i międzynarodowymi\nwspółtworzenie programów współpracy międzynarodowej Fundacji\nrekrutowanie pracowników i praktykantów do prowadzonych programów współpracy międzynarodowej\nkontakt telefoniczny i e-mailowy z potencjalnymi klientami, sponsorami, beneficjentami oraz partnerami organizacji, w tym partnerami z III sektora zarówno z kraju jak i za granicy\nwykonywanie innych zadań zleconych z zakresu marketingu politycznego",
            'narzędzia' => "minimalny wymiar godzinowy praktyk – 160 h\nstatus studenta (preferowane kierunki: politologia, stosunki międzynarodowe oraz pokrewne) – przy praktykach uczelnianych\nznajomość pakietu MS Office\nsamodzielność, dobra organizacja pracy, umiejętność pracy zespołowej\nzaangażowanie, sumienność i dokładność w wykonywaniu zadań\nefektywne komunikowanie się z otoczeniem w miejscu pracy\nwysoka kultura osobista\ngotowość do nauki nowych rzeczy\nchęć zdobycia praktycznej wiedzy z zakresu marketingu politycznego",
            'obraz' => "/images/internships/marketing_polityczny.png"
        ]);

        Internship::create([
            'nazwa' => "Specjalista ds. HR",
            'opis' => "Specjalista ds. HR zajmuje się planowaniem ścieżki kariery pracowników firmy, organizowaniem szkoleń, mających rozszerzyć ich kompetencje, a także pozyskiwaniem nowych pracowników.",
            'obowiązki' => "poznanie zakresu działania, strategii, wyników ekonomicznych, pozycji rynkowej, mikro- i makro-otoczenia, głównych interesariuszy;\npoznanie struktury majątkowej i organizacyjnej, obiegu dokumentacji, sposobu działania jednostek wewnętrznych i zależnych, prac wykonywanych przez pracowników w poszczególnych działać;\npoznanie systemu zarządzania, zasad przepływu informacji, sposobów podejmowania decyzji i kontroli;\nobserwacja oraz uczestniczenie w bieżącej działalności operacyjnej jednostki;\nzapoznanie ze specyfiką funkcjonowania poszczególnych działów jednostki, w tym zadaniami funkcjonalnymi przez nie realizowanymi, ze szczególnym uwzględnieniem działu HR;\ndoskonalenie wiedzy i umiejętności związanych z wybranym przez studenta kierunkiem studiów i specjalnością w obszarze zarządzania zasobami ludzkimi, w tym elementami planowania, doboru kadr, procesów adaptacyjnych, motywowania, rozwoju, kontroli i oceny pracowniczej;\nzapoznanie z procedurą przygotowania dokumentacji, systemu ewidencji danych oraz jej wykorzystania w procesach decyzyjnych;\nrealizowanie elementarnych zadań związanych z procesem zarządzania (np. analiza danych wtórnych, przygotowanie pism itp.);\nrealizacja zadań wynikających z administracji kadrowej oraz ustalaniem optymalnego poziomu zatrudnienia.\npoznanie przepisów Prawa Pracy, Prawa Ubezpieczeń Społecznych, Prawa Podatkowego, związanych z zatrudnieniem pracowników.",
            'narzędzia' => "CV Timeline lub Workable\nHireVue / Zoom/ Skype\nDevskiller\nBambooHR\nWorksmile (Fitqbe)\nAsana\nEvernote\nAppint.ly\neRecruiter",
            'obraz' => "/images/internships/specjalista_ds_hr.png"
        ]);

        Internship::create([
            'nazwa' => "Zarządzanie",
            'opis' => null,
            'obowiązki' => "zapoznanie się z procesem zarządzania i zasadami funkcjonowania organizacji (forma prawna, struktura organizacyjna, zasady organizacji pracy i podziału kompetencji, procedury, procesy planowania i kontroli)\nnabycie wiedzy teoretycznej i umiejętności praktycznych z zakresu zarządzania poprzez obserwację i współuczestnictwo w realizacji zadań związanych z rozwiązywaniem problemów praktycznych w tym obszarze\nzapoznanie się z aspektami etycznymi środowiska pracy, w szczególności, odpowiedzialnością, kształtowaniem relacji interpersonalnych, dyscypliną, funkcjonowaniem hierarchii organizacyjnej oraz zachowań organizacyjnych\nrozwój umiejętności pracy w zespole, jak i na samodzielnym stanowisku\nrozwój umiejętności efektywnego komunikowania się, negocjowania i współpracy z osobami z różnych środowisk\nrozwój umiejętności organizatorskich\nrozwój umiejętności poznawczych (analiza, synteza, krytyczna ocena i inne)\nudział w projektach rozwojowych z zakresu zarządzania\nutrzymywanie pozytywnych relacji biznesowych z klientami\nwspółuczestnictwo w kreowaniu i realizacji projektów organizacji uwzględniając różne aspekty m.in. prawne, ekologiczne\nsporządzanie ofert czy dokumentów takich jak Statut\nnadzór nad realizacją umów i projektów\nwspieranie działań poszczególnych działów organizacji oraz przyjmowanie różnych ról w grupach (wykonawca, organizator, kierownik)\nrozpoznawanie, diagnozowanie i rozwiązywanie problemów związanych z funkcjonowaniem i procesem zarządzania: planowaniem, organizowaniem, motywowaniem, kontrolą i koordynacją – raportowanie działań\nocenianie wpływu otoczenia na zjawiska i procesy zarządzania oraz proponowanie kolejnych działań organizacji\npozyskiwanie, analizowanie i ewidencja materiałów źródłowych z różnych działów organizacji i formułowanie na ich podstawie wniosków\nbudowanie pozytywnego wizerunku organizacji za pomocą social mediów i e-mail\nkontakt e-mailowy i telefoniczny z klientami\nwykonywanie innych zadań zleconych z zakresu zarządzania",
            'narzędzia' => "minimalny wymiar godzinowy praktyk – 160 h\nstatus studenta (preferowane kierunki: zarządzanie, zarządzanie w biznesie, prawo, prawo w biznesie i pokrewne) – przy praktykach uczelnianych\nznajomość pakietu MS Office\nsamodzielność, dobra organizacja pracy, umiejętność pracy zespołowej\nwysoka kultura osobista\ngotowość do nauki nowych rzeczy\nchęć zdobycia praktycznej wiedzy z zakresu zarządzania",
            'obraz' => "/images/internships/zarzadzanie.png"
        ]);

        Internship::create([
            'nazwa' => "Administracja",
            'opis' => null,
            'obowiązki' => "zapoznanie się z daną organizacją i zasadami jej funkcjonowania (forma prawna, struktura organizacyjna, zasady organizacji pracy i podziału kompetencji, procedury, procesy planowania i kontroli)\nzapoznanie się z obiegiem dokumentów i podstawowymi procedurami podejmowania decyzji\nobsługę korespondencji przychodzącej i wychodzącej\nwypełnianie, weryfikowanie poprawności i kompletowanie niezbędnej dokumentacji dla organizacji\nprzygotowywanie projektów dokumentów, pism urzędowych, umów oraz raportów zgodnie z zapotrzebowaniem organizacji\narchiwizację dokumentów\nwykonywanie podstawowych czynności administracyjnych i prac biurowych na określonych stanowiskach pracy oraz wykorzystanie w tym celu technik komputerowych\nadministrowanie bazą danych\nwprowadzanie danych i skanowanie dokumentów do systemu\norganizację spotkań z interesariuszami\ndoskonalenie umiejętności pracy zespołowej, efektywnego wykorzystania czasu pracy, odpowiedzialności za wykonanie powierzonych zadań\nzapoznanie się z zasadami właściwej obsługi interesantów oraz bezpośrednią lub pośrednią obsługą klienta\nkontakt e-mailowy i telefoniczny z interesariuszami organizacji\nwykonywanie innych zleconych czynności administracyjnych i prac biurowych",
            'narzędzia' => "minimalny wymiar godzinowy praktyk – 160 h\nstatus studenta (preferowane kierunki: administracja i pokrewne) – przy praktykach uczelnianych\nznajomość pakietu MS Office\nsamodzielność, dobra organizacja pracy\numiejętność nadawania zadaniom priorytetów zgodnie z potrzebami organizacji oraz podzielność uwagi\numiejętność pracy pod presją czasu\nzaangażowanie i dokładność w wykonywaniu zadań\nefektywne komunikowanie się z otoczeniem w miejscu pracy\nwysoka kultura osobista\nłatwość w nawiązywaniu i utrzymywaniu kontaktów z klientami\ngotowość do nauki nowych rzeczy",
            'obraz' => "/images/internships/administracja.png"
        ]);

        Internship::create([
            'nazwa' => "Redaktor",
            'opis' => "Redaktor to osoba dokonująca redakcji tekstu (książki, artykułów w czasopismach, encyklopediach i na stronach WWW, jak również w programach radiowych i telewizyjnych). Często ma znaczny wpływ na ostateczną postać publikacji – a czasami decyduje też o tym, czy daną publikację odrzucić, czy przyjąć do druku. Najważniejszą pozycję wśród redaktorów zajmuje redaktor naczelny, podejmujący strategiczne decyzje w sprawach danego pisma.",
            'obowiązki' => "zapoznanie się ze strukturą organizacyjną redakcji\npoznanie zasad pracy działów redakcyjnych\nrozpoznanie zadań i funkcji, jakie w strukturze redakcyjnej pełni sekretariat redakcji i redaktor (redaktorzy) prowadzący\npoznanie zasad obiegu materiału redakcyjnego (tekstów, zdjęć i innych materiałów ilustracyjnych)\npoznanie zasad składu, stosowania wyróżnień w tekście, a także uczestniczenie (obserwacja) w procesie łamania kolumn\npoznanie „poetyki” tytułów nagłówkowych stosowanych w redakcji, a także zasady stosowania nadtytułów, podtytułów i śródtytułów\ndokumentowanie tematów, pisanie tekstów informacyjnych z zachowaniem odpowiedniej konstrukcji tekstów informacyjnych (podział na lid i body)\nzgłaszanie do wykonania bądź przyjmowanie do wykonania tematu sondy ulicznej\npoznanie ogólnych zasad redagowania tekstu informacyjnego i/lub wszelkich działań komunikacyjnych właściwych dla typu działalności prowadzonej w miejscu odbywania praktyki (np. w przypadku redakcji prasowej lub nowych mediów – programu telewizyjnego i radiowego oraz komponowania zawartości gazety lub programu)\nobserwowanie wszystkich etapów pracy nad kształtowaniem komunikatu\nsamodzielne przygotowanie materiału informacyjnego lub projektu kampanii komunikacyjnej – odpowiednio do miejsca realizowania praktyk",
            'narzędzia' => "Monday.com\nSmartsheet\nBasecamp\nTrello",
            'obraz' => "/images/internships/redaktor.png"
        ]);

        Internship::create([
            'nazwa' => "Prawo",
            'opis' => null,
            'obowiązki' => "zapoznanie się z daną organizacją i zasadami jej funkcjonowania (forma prawna, struktura organizacyjna, zasady organizacji pracy i podziału kompetencji, procedury, procesy planowania i kontroli)\nzapoznanie się zasadami przepływu informacji i dokumentacji w ramach organizacji\nzapoznanie się z zasadami archiwizacji dokumentacji prawniczej w organizacji\nzapoznanie się z przepisami regulującymi działanie organizacji oraz ich praktycznym wykorzystaniem\nnabycie umiejętności praktycznego przygotowywania dokumentacji, pism urzędowych dla organizacji\nnabycie umiejętności analizowania przepisów prawnych w praktyce\nwsparcie organizacji w załatwianiu spraw w sądach i urzędach\nanaliza spraw prawnych prowadzonych przez organizację\nanaliza stanowiska orzecznictwa i doktryny pod kątem spraw prawnych prowadzonych przez organizację\nwyszukiwanie dotacji na organizacji oraz analiza wymogów formalnych, które musi spełnić\nwykonywanie innych zadań zleconych z zakresu prawa",
            'narzędzia' => "minimalny wymiar godzinowy praktyk – 160 h\nstatus studenta (preferowane kierunki: prawo oraz pokrewne) – przy praktykach uczelnianych\nznajomość pakietu MS Office\nsamodzielność, dobra organizacja pracy, umiejętność pracy zespołowej\nzaangażowanie, sumienność i dokładność w wykonywaniu zadań\nefektywne komunikowanie się z otoczeniem w miejscu pracy\nwysoka kultura osobista\ngotowość do nauki nowych rzeczy\nchęć zdobycia praktycznej wiedzy z zakresu prawa",
            'obraz' => "/images/internships/prawo.png"
        ]);

        Internship::create([
            'nazwa' => "Księgowość",
            'opis' => null,
            'obowiązki' => "zapoznanie się z daną organizacją i zasadami jej funkcjonowania (forma prawna, struktura organizacyjna, zasady organizacji pracy i podziału kompetencji, procedury, procesy planowania i kontroli)\nzapoznanie się zasadami przepływu informacji i dokumentacji księgowej w ramach organizacji\nzapoznanie się z zasadami archiwizacji dokumentacji księgowej z zastrzeżeniem ochrony danych osobowych\nzapoznanie się z formami rozliczeń pieniężnych z kontrahentami jednostki organizacyjnej\nzapoznanie się z metodami amortyzacji środków trwałych stosowanymi w jednostce organizacyjnej\nnabycie umiejętności praktycznych sporządzania dokumentów obrotu pieniężnego i innych dowodów księgowych\nnabycie umiejętności praktycznych obliczania kwoty rocznego odpisu amortyzacji wybranych środków trwałych\nnabycie umiejętności rozróżniania dowodów potwierdzających operacje gospodarcze i zakwalifikowanie ich do ujęcia w księgach rachunkowych\nzapoznanie się z planem i dokumentacją inwentaryzacji\nsporządzanie dokumentów obrotu pieniężnego i innych dowodów księgowych\nkontrola wstępna dowodów księgowych\nodczytywanie zdarzeń gospodarczych z dowodów księgowych\nokreślanie okresu przechowywania różnych dowodów i dokumentów księgowych występujących w organizacji\nokreślanie podstawowych wymogów dotyczących ksiąg rachunkowych prowadzonych przy użyciu komputera\nobsługa programów komputerowych do księgowania operacji gospodarczych stosowanych w organizacji\nobliczanie kwoty rocznego odpisu amortyzacji wybranych środków trwałych\nksięgowanie wybranych operacji gospodarczych na podstawie dowodów źródłowych w programie finansowo – księgowym\nwykonywanie innych zleconych czynności z zakresu rachunkowości",
            'narzędzia' => "minimalny wymiar godzinowy praktyk – 160 h\nstatus studenta (preferowane kierunki: finanse i rachunkowość oraz pokrewne) – przy praktykach uczelnianych\nznajomość pakietu MS Office\nsamodzielność, dobra organizacja pracy, umiejętność pracy zespołowej\nzaangażowanie, sumienność i dokładność w wykonywaniu zadań\nefektywne komunikowanie się z otoczeniem w miejscu pracy\nwysoka kultura osobista\ngotowość do nauki nowych rzeczy\nchęć zdobycia praktycznej wiedzy z zakresu rachunkowości",
            'obraz' => "/images/internships/ksiegowosc.png"
        ]);
    }
}
